import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';

import { Layout } from '../components/Layout/layout';

import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Animal Social Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Layout>
          <Link href="/sign_in">Sign_in</Link>
          <main className={styles.main}>Animal social media</main>
        </Layout>
      </div>
    </>
  );
}
